services:
  app:
    build: ./tests/docker
    volumes:
      - .:/app
      - $HOME/.composer/cache:/root/.composer/cache
    working_dir: /app

  database:
    image: mysql:8.0
    command: --local-infile
    environment:
      MYSQL_ROOT_PASSWORD: loadfile-testing
      MYSQL_DATABASE: loadfile
      MYSQL_USER: loadfile
      MYSQL_PASSWORD: loadfile-testing
